'\" t
.\"     Title: eprintf
.\"    Author: [see the "AUTHORS" section]
.\" Generator: Asciidoctor 1.5.4
.\"      Date: 2016-09-07
.\"    Manual: CS50 Programmer's Manual
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "EPRINTF" "3" "2016-09-07" "\ \&" "CS50 Programmer\(aqs Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
eprintf \- pritns an error message to stderr.
.SH "SYNOPSIS"
.sp
\fB#include <cs50.h>\fP
.sp
\fBvoid eprintf(const string format, ...);\fP
.SH "DESCRIPTION"
.sp
Prints an error message, formatted like \fBprintf(3)\fP, to the standard error, prefixing it with the program\(cqs name as well as the file and line number from which the function was called. See \fBprintf(3)\fP for more on formatting.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
eprintf("%s\(rsn", "this is an error");
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
printf(3)