= get_long_long(3)
:manmanual: CS50 Programmer's Manual
:mansource: CS50
:man-linkstyle: pass:[blue R < >]

== NAME

get_long_long - prompts user for a line of text from stdin and returns the equivalent long long

== SYNOPSIS

*#include <cs50.h>*

*long long get_long_long(const string format, ...);*

== DESCRIPTION

Prompts user for a line of text from standard input and returns the equivalent long long; if the text does not represent a long long or would cause overflow, user is reprompted.

The prompt is formatted like *printf(3)*.

== RETURN VALUE

Returns the long long equivalent to the line read from stdin in [*LLONG_MIN*, *LLONG_MAX*). If line can't be read, returns *LLONG_MAX*.

== EXAMPLE

    // attempt to read long long from stdin
    long long ll = get_long_long("%s: ", "Enter long long");

    // ensure long long was read
    if (ll != LLONG_MAX)
    {
        printf("You entered: %lld\n", ll);
    }

== SEE ALSO

    get_char(3), get_double(3), get_float(3), get_int(3), get_string(3),
    printf(3)
