= get_double(3)
:manmanual: CS50 Programmer's Manual
:mansource: CS50
:man-linkstyle: pass:[blue R < >]

== NAME

get_double - prompts user for a line of text from stdin and returns the equivalent double

== SYNOPSIS

*#include <cs50.h>*

*double get_double(const string format, ...);*

== DESCRIPTION

Prompts user for a line of text from standard input and returns the equivalent double as precisely as possible; if text does not represent a double or would cause underflow or overflow, user is reprompted.

The prompt is formatted like *printf(3)*.

== RETURN VALUE

Returns the double equivalent to the line read from stdin in [*DBL_MIN*, *DBL_MAX*), as precisely as possible. If line can't be read, returns *DBL_MAX*.

== EXAMPLE

    // attempt to read double from stdin
    double d = get_double("Enter double: ");

    // ensure double was read
    if (d != DBL_MAX)
    {
        printf("You entered: %f\n", d);
    }

== SEE ALSO

    get_char(3), get_float(3), get_int(3), get_long_long(3),
    get_string(3), printf(3)
